version: '3.8'

services:
  extractous-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESSERACT_LANGUAGES: ${TESSERACT_LANGUAGES:-eng+rus}
    container_name: extractous-api
    restart: unless-stopped
    ports:
      - "8280:8080"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - TESSERACT_LANGUAGES=${TESSERACT_LANGUAGES:-eng+rus}
      - ACTIX_CORS_ORIGIN=${ACTIX_CORS_ORIGIN:-*}
      - ACTIX_BEARER_TOKEN=${ACTIX_BEARER_TOKEN}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./temp_uploads:/app/temp_uploads
    networks:
      - extractous-network

networks:
  extractous-network:
    driver: bridge

# Example usage:
# TESSERACT_LANGUAGES=eng+rus+fra+deu docker-compose up --build
